apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql
    release: sonarqube
    role: master
  name: data-sonarqube-postgresql-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs
  volumeMode: Filesystem
