apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "4"
    persistentvolumeclaims: "4"
    pods: "4"
    replicationcontrollers: "4"
    secrets: "4"
    services: "4"
    services.loadbalancers: "2"
