images:
  version: latest
  imagePullPolicy: Always
  
storageClasses:
  default:
    name: nfs
    create: false
    provisioner: kubernetes.io/aws-ebs
    reclaimPolicy: Delete
    parameters:
      type: gp2
      fsType: ext4
  shared:
    name: nfs
    create: false
    provisioner: nfs
    reclaimPolicy: Delete
    parameters:
      mountOptions: vers=4.1


networkPolicies:
  enabled: false
  dnsPorts:
  - 53
  - 8053


gitRepositoryStorage:
  externalPVC:
    use: false
    name: git-repositories-pvc
  size: 5Gi

caCert:

ingress:
  enabled: true
  host: gerrit.tccmurilo.sj.ifsc.edu.br
  maxBodySize: 50m
  tls:
    enabled: false
    secret:
      create: true

gitGC:
  image: k8sgerrit/git-gc

  schedule: 0 6,18 * * *

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi

  logging:
    persistence:
      enabled: true
      size: 1Gi


gerrit:
  images:
    gerritInit: k8sgerrit/gerrit-init
    gerrit: k8sgerrit/gerrit

  replicas: 1
  updatePartition: 0

  # The memory limit has to be higher than the configures heap-size for Java!
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

  persistence:
    enabled: true
    size: 10Gi

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 5

  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 1

  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 30


  service:
    type: ClusterIP
    http:
      port: 8090
    ssh:
      enabled: false
      port: 29418

  index:
    type: lucene

  plugins:
    packaged:
    - commit-message-length-validator
    - download-commands
    - replication
    - reviewnotes
    cache:
      enabled: false
      size: 1Gi

  etc:

    config:
      gerrit.config: |-
        [gerrit]
          basePath = git # FIXED
          serverId = gerrit-1
          canonicalWebUrl = http://gerrit.tccmurilo.sj.ifsc.edu.br/
          disableReverseDnsLookup = true
        [index]
          type = LUCENE
          onlineUpgrade = false # FIXED
        [auth]
          type = LDAP
        [ldap]
          server = XXXXXXXXXXXXXXXXX
          username = XXXXXXXXXXXXXXXXXXXX
          password = XXXXXXXXXXXX
          accountBase = XXXXXXXXXXXXXXXXXXXXXXX
          accountPattern = (&(uid=${username}))
          supportAnonymous = false
        [httpd]
          listenUrl = proxy-http://*:8080
          requestLog = true
        [sshd]
          listenAddress = off
        [transfer]
          timeout = 120 s
        [user]
          name = Admin
          email = example@example.com
          anonymousCoward = Unnamed User
        [cache]
          directory = cache
        [container]
          user = gerrit # FIXED
          javaHome = /usr/lib/jvm/java-11-openjdk # FIXED
          javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore # FIXED
          javaOptions = -Xms200m
          javaOptions = -Xmx4g

      replication.config: |-
        [gerrit]
          autoReload = false
          replicateOnStartup = true
          defaultForceUpdate = true

         [remote "gitlab"]
          url = http://gitlab.tccmurilo.sj.ifsc.edu.br/cluster_rke/${name}.git
          replicationDelay = 0
          timeout = 30

    secret:
      secure.config: |-
         [remote "gitlab"]
         username = XXXXXXXXXXXX
         password = XXXXXXXXXXXX
