apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
#  namespace: teste
#  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-operator
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-operator
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: default
#    namespace: teste
roleRef:
  kind: ClusterRole
  name: cluster-operator
  apiGroup: rbac.authorization.k8s.io
