# Values for gitlab/gitlab chart on GKE
certmanager-issuer:
  email: murilo.bauer90@gmail.com
global:
  appConfig:
    ldap:
      enabled: true
      preventSignin: false
      servers:
        main:
#          bind_dn: 'cn=mbauer,ou=Developer,dc=sj,dc=ifsc,dc=edu,dc=br'
          bind_dn: 'cn=admin,dc=sj,dc=ifsc,dc=edu,dc=br'
#          base: 'ou=Developer,dc=sj,dc=ifsc,dc=edu,dc=br'
          base: 'dc=sj,dc=ifsc,dc=edu,dc=br'
          host: '191.36.8.57'
          label: 'LDAP'
          port: 389
          uid: 'uid'
#          user_filter: '\\(sAMAccountName=%u\\)'
#          user_filter: 'objectclass=*'
#	   user_filter: '(&(objectClass=posixAccount))'
          password:
            key: password
            secret: ldap-secret
#          encryption: 'plain'
  edition: ce
  hosts:
    domain: sj.ifsc.edu.br
    https: false
    externalIP: 191.36.8.57
  ingress:
    configureCertmanager: false
#    class: "nginx"
#    enabled: true
    tls:
      enabled: false
#      secretName: tls-tcc
      secretName: ingress-default-cert
    annotations:
      "nginx.ingress.kubernetes.io/ssl-redirect": "false"
prometheus:
  install: true
certmanager:
  install: false
nginx-ingress:
  enabled: false
gitlab-runner:
  install: false
redis:
  install: true
gitlab:
  gitaly:
    persistence:
      storageClass: nfs
postgresql:
  persistence:
    storageClass: nfs
minio:
  persistence:
    storageClass: nfs
redis:
  master:
    persistence:
      storageClass: nfs
prometheus:
  server:
    persistence:
      storageClass: nfs
