controller:
  jenkinsUrlProtocol: "https"
  jenkinsUrl: "gerrit.tccmurilo.sj.ifsc.edu.br"
  #installPlugins:
  #  - gitlab-plugin:1.5.12
  #  - kubernetes:1.29.4
  #  - workflow-aggregator:2.6
  #  - git:4.7.1
  #  - configuration-as-code:1.51
  installLatestPlugins: true
  ingress:
    enabled: true
    # ex /github-webhook
    paths: []
    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    # For Kubernetes v1.19+, use 'networking.k8s.io/v1'
    apiVersion: "networking.k8s.io/v1"
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # ingressClassName: nginx
    # configures the hostname e.g. jenkins-external.example.com
    hostName:
    tls:
     - secretName: jenkins-external.example.com
       hosts:
         - gerrit.tccmurilo.sj.ifsc.edu.br
persistence:
  enabled: true
  existingClaim:
  storageClass: nfs
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
