controller:
  adminUser: "admin"
  adminPassword: "tccmurilo2021"
  jenkinsUrlProtocol: "https"
  jenkinsUrl: "jenkins.tccmurilo.sj.ifsc.edu.br"
  installPlugins:
    - gitlab-plugin
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  installLatestPlugins: true
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    kubernetes.io/ingress.class: nginx
    hostName:
    tls:
     - secretName: ingress-default-cert
       hosts:
         - jenkins.tccmurilo.sj.ifsc.edu.br
persistence:
  enabled: true
  existingClaim:
  storageClass: nfs
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
  volumes:
    - name: jenkins-ssh-key
      secret:
        secretName: jenkins-ssh-key
        defaultMode: 0600
  mounts:
    - mountPath: /var/jenkins_home/.ssh
      name: jenkins-ssh-key
      readOnly: true
